#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════
# DotGhostBoard — Local AppImage Builder
# ═══════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

source "$SCRIPT_DIR/lib/build_common.sh"

APP_NAME="DotGhostBoard"
VERSION="$(get_version)"
ARCH="x86_64"
APPDIR="${APP_NAME}.AppDir"
OUTPUT_APPIMAGE="${APP_NAME}-${VERSION}-${ARCH}.AppImage"

echo "========================================================"
echo "👻 Building ${APP_NAME} v${VERSION} AppImage"
echo "========================================================"

# Clean up any old artifacts
rm -rf "$APPDIR" "$OUTPUT_APPIMAGE"

# Ensure executable binary exists or build it
BINARY="dist/dotghostboard-app/dotghostboard-app"
if [ ! -x "$BINARY" ]; then
    echo "📦 Compiled binary not found or not executable, invoking build_binary.sh..."
    bash "$SCRIPT_DIR/build_binary.sh"
fi

echo "🔨 Creating AppDir structure..."
mkdir -p "$APPDIR/usr/bin"
mkdir -p "$APPDIR/usr/share/applications"
mkdir -p "$APPDIR/usr/share/icons/hicolor/256x256/apps"
mkdir -p "$APPDIR/usr/share/metainfo"

# Copy files generated by PyInstaller
cp -a dist/dotghostboard-app/. "$APPDIR/usr/bin/"

# Create AppRun launcher (clean runtime: dynamically selects Wayland/X11 without manual LD_LIBRARY_PATH injection)
cat > "$APPDIR/AppRun" << 'LAUNCHER'
#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"

export PATH="${HERE}/usr/bin:${PATH}"
export QT_LOGGING_RULES="*.debug=false;qt.dbus.*=false"

cd "${HERE}/usr/bin"
exec ./dotghostboard-app "$@"
LAUNCHER
chmod 755 "$APPDIR/AppRun"

# Create desktop entry
cat > "$APPDIR/dotghostboard.desktop" << 'DESKTOP'
[Desktop Entry]
Type=Application
Name=DotGhostBoard
GenericName=Clipboard Manager
Comment=Advanced clipboard manager for Linux — DotSuite
Exec=dotghostboard-app
Icon=dotghostboard
Categories=Utility;
Keywords=clipboard;copy;paste;pin;ghost;dotsuite;
Terminal=false
DESKTOP

cp "$APPDIR/dotghostboard.desktop" "$APPDIR/usr/share/applications/"

# Copy icons and metadata
if [ -f "data/icons/icon_256.png" ]; then
    cp data/icons/icon_256.png "$APPDIR/dotghostboard.png"
    cp data/icons/icon_256.png "$APPDIR/usr/share/icons/hicolor/256x256/apps/dotghostboard.png"
fi
if [ -f data/dotghostboard.appdata.xml ]; then
    cp data/dotghostboard.appdata.xml "$APPDIR/usr/share/metainfo/com.github.kareem2099.dotghostboard.metainfo.xml"
fi

# Verify appimagetool exists locally
APPIMAGETOOL="${APPIMAGETOOL:-$ROOT_DIR/appimagetool}"
if [ ! -x "$APPIMAGETOOL" ]; then
    if command -v appimagetool >/dev/null 2>&1; then
        APPIMAGETOOL="$(command -v appimagetool)"
    else
        echo "❌ appimagetool not found or not executable:" >&2
        echo "   $APPIMAGETOOL" >&2
        echo "   Please place verified appimagetool at $ROOT_DIR/appimagetool or set \$APPIMAGETOOL." >&2
        exit 1
    fi
fi

echo "📦 Packaging AppImage using $APPIMAGETOOL..."
ARCH=x86_64 "$APPIMAGETOOL" "$APPDIR" "$OUTPUT_APPIMAGE"

# Clean up temporary AppDir after completion
echo "🧹 Cleaning up temporary AppDir..."
rm -rf "$APPDIR"

echo ""
echo "✅ Success! Your AppImage build is ready:"
echo "   $(pwd)/${OUTPUT_APPIMAGE}"