#!/bin/bash
# ═══════════════════════════════════════════════════════
# DotGhostBoard — Local AppImage Builder (v1.5.0 Nexus)
# ═══════════════════════════════════════════════════════

set -e

APP_NAME="DotGhostBoard"
# Get version from README or default to 1.4.1
VERSION=$(grep -oP 'version-v\K[0-9]+\.[0-9]+\.[0-9]+' README.md | head -1 || echo "1.5.1")
ARCH="x86_64"
APPDIR="${APP_NAME}.AppDir"

echo "🛡️ Checking Dependencies..."
# Ensure required libraries are installed in current environment
pip install PyQt6 Pillow cryptography pyinstaller --quiet

echo "🎨 Generating Fresh Icons..."
python3 scripts/generate_icon.py

echo "🚀 Compiling with PyInstaller (Local Context)..."
# Added --hidden-import and --collect-all to ensure cryptography is bundled locally
pyinstaller --noconsole --onedir \
    --add-data "data:data" \
    --hidden-import "PyQt6.sip" \
    --hidden-import "cryptography" \
    --collect-all "cryptography" \
    --name dotghostboard main.py

echo "🔨 Building ${APP_NAME} v${VERSION} AppImage structure..."

# Clean up any old artifacts
rm -rf "$APPDIR" "dist/${APP_NAME}-${VERSION}-${ARCH}.AppImage"

# Create AppDir structure
mkdir -p "$APPDIR/usr/bin"
mkdir -p "$APPDIR/usr/share/applications"
mkdir -p "$APPDIR/usr/share/icons/hicolor/256x256/apps"
mkdir -p "$APPDIR/usr/share/metainfo"

# Copy files generated by PyInstaller
cp -r dist/dotghostboard/* "$APPDIR/usr/bin/"

# Create AppRun launcher (the beating heart of AppImage)
cat > "$APPDIR/AppRun" << 'LAUNCHER'
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/bin:${LD_LIBRARY_PATH}"
export QT_QPA_PLATFORM=xcb
export QT_LOGGING_RULES="*.debug=false;qt.dbus.*=false"

cd "${HERE}/usr/bin"
exec ./dotghostboard "$@"
LAUNCHER
chmod +x "$APPDIR/AppRun"

# Create desktop entry
cat > "$APPDIR/dotghostboard.desktop" << 'DESKTOP'
[Desktop Entry]
Type=Application
Name=DotGhostBoard
GenericName=Clipboard Manager
Comment=Advanced clipboard manager for Linux — DotSuite
Exec=dotghostboard
Icon=dotghostboard
Categories=Utility;
Keywords=clipboard;copy;paste;pin;ghost;dotsuite;
Terminal=false
DESKTOP

cp "$APPDIR/dotghostboard.desktop" "$APPDIR/usr/share/applications/"

# Copy icons and metadata
cp data/icons/icon_256.png "$APPDIR/dotghostboard.png"
cp data/icons/icon_256.png "$APPDIR/usr/share/icons/hicolor/256x256/apps/dotghostboard.png"
if [ -f data/dotghostboard.appdata.xml ]; then
    cp data/dotghostboard.appdata.xml "$APPDIR/usr/share/metainfo/com.github.kareem2099.dotghostboard.metainfo.xml"
fi

# Download appimagetool if not present locally
if [ ! -f appimagetool ]; then
    echo "📥 Downloading appimagetool..."
    wget -q "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${ARCH}.AppImage" -O appimagetool
    chmod +x appimagetool
fi

echo "📦 Packaging AppImage..."
# Run tool to convert folder into single AppImage file
./appimagetool "$APPDIR" "${APP_NAME}-${VERSION}-${ARCH}.AppImage"

# Clean up temporary files after completion
echo "🧹 Cleaning up temporary files..."
rm -rf "$APPDIR"
rm -rf build
# Leave dist folder so you can inspect files before compression

echo ""
echo "✅ Success! Your local build is ready:"
echo "   $(pwd)/${APP_NAME}-${VERSION}-${ARCH}.AppImage"